# Site settings
title: My GitHub Pages Site
description: A simple site for showcasing my projects and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
github_username: username

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: /:categories/:title/
paginate: 5 # Number of posts to show per page

# Google Analytics
google_analytics: UA-XXXXXXXX-X # Your Google Analytics tracking ID

# Social links
social_links:
  twitter: https://twitter.com/sparkysparo
  github: https://github.com/sparkysparo
  linkedin: https://www.linkedin.com/in/uzoegwu-paschal/

# Author settings
author:
  name: Paschal Uzoegwu
  email: sparkysparo@yahoo.com
  twitter: yourhandle
  image: /assets/author-profile.jpg  # Path to your author profile image

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Paschal Uzoegwu

# Custom variables
custom_var: custom_value

# Configuration for Jekyll Feed
feed:
  path: atom.xml

# Projects
projects:
  - name: Analysis of Happiness Regional Variations
    description: Used Python to explore happiness scores across regions, identifying key influencing factors.
    link: https://github.com/sparkysparo/Analysis-of-Happiness-Regional-Variations.Paschal-Uzoegwu-21063051.ADS-Assignment

  - name: Analysis of Bank Authentication Data
    description: Employed clustering algorithms to detect patterns in transaction data, improving fraud detection.
    link: https://github.com/sparkysparo/Analysis-of-Bank-Authentication-Data.Paschal-Uzoegwu-21063051.ADS-Project-On-Clustering-And-Fitting

  - name: Investigating Netflix Movies
    description: Analyzed movie length trends on Netflix using Python, contributing to content strategy planning.
    link: https://github.com/sparkysparo/Investigating-Netflix-Movies

# Certifications
certifications:
  - name: Data Science Orientation
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Excel To Power BI
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Data Visualization (Kaggle)
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Microsoft Power BI
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Foundations of Data Science: K Means Clustering in Python
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Excel For Data Analysis
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: SQL (DataCamp)
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Data Science Diploma (Allison)
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/

  - name: Data Analyst Associate
    link: https://www.linkedin.com/in/uzoegwu-paschal/details/certifications/
