# Site settings
title: My GitHub Pages Site
description: A simple site for showcasing my projects and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
github_username: username

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: /:categories/:title/
paginate: 5 # Number of posts to show per page

# Google Analytics
google_analytics: UA-XXXXXXXX-X # Your Google Analytics tracking ID

# Social links
social_links:
  twitter: https://twitter.com/yourhandle
  github: https://github.com/yourusername
  linkedin: https://www.linkedin.com/in/yourprofile/

# Author settings
author:
  name: Your Name
  email: your-email@example.com
  twitter: yourhandle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Your Name

# Custom variables
custom_var: custom_value

# Configuration for Jekyll Feed
feed:
  path: atom.xml
